spring:
  banner:
    location: classpath:banner.txt

logging:
  level:
    root: INFO

server:
  port: 8443
  ssl:
    enabled: true
    key-store-type: JKS
    key-store: classpath:identity.jks
    key-store-password: secret
    key-password: secret
    client-auth: need
#    key-alias: saas-gw-ms
    trust-store-type: JKS
    trust-store: classpath:truststore.jks
    trust-store-password: secret
