spring:
  banner:
    location: classpath:banner.txt

logging:
  level:
    root: INFO

server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.jks
    key-store-password: secret
    key-password: secret
    key-alias: saas-gw-ms
    key-store-type: JKS
#    key-store-provider: SUN
    trust-store: classpath:truststore.jks
    trust-store-password: secret
    trust-store-type: JKS
