spring:
  application:
    name: f5
---
#server:
#  port: 9001
#  ssl:
#    enabled: true
#    client-auth: need
#    key-store: classpath:keystore.jks
#    key-store-password: secret
#    key-alias: f5
#    key-store-type: JKS
#    trust-store: classpath:truststore.jks
#    trust-store-password: secret
#    trust-store-type: JKS